### ISSUE TITLE
 InternalServerError: Cannot complete OAuth process. Could not find an OAuth cookie for shop url ...

### ISSUE THREAD

**Issue by valorloff** [Shopify/shopify-app-node#585]
# Issue summary
Issues navigations after app been installed

Write a short description of the issue here ↓
Installation and billing app parts was successful, but attempt navigate to index route return 
`POST https://ngrok.XXXX/graphql 401 (Unauthorized)`

## Expected behavior
Navigation worked fine in the old api without any problem

What do you think?
My opinion: problem with session tokens, possible reason: SSR rendered page lost session token, but not regenerate new one

## Actual behavior

What actually happens?
Click nav link results browser error: 'bad request'. If reload page: server error: 
```
 InternalServerError: Cannot complete OAuth process. Could not find an OAuth cookie for shop url: XXX.myshopify.com
      at Object.throw (/home/valaoffice/projects/shopify-dst/node_modules/koa/lib/context.js:97:11)
      at /home/valaoffice/projects/shopify-dst/node_modules/@shopify/koa-shopify-auth/dist/src/auth/index.js:100:42
      at step (/home/valaoffice/projects/shopify-dst/node_modules/tslib/tslib.js:141:27)
      at Object.throw (/home/valaoffice/projects/shopify-dst/node_modules/tslib/tslib.js:122:57)
      at rejected (/home/valaoffice/projects/shopify-dst/node_modules/tslib/tslib.js:113:69)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
If i delete app from devStore, then install it back on, installation process and initial page works nice.

- Browser: Chrome
- Device: PC
- Operating System: Ubuntu 20

In the docs, you mentioned that tokens need to be written to the database for later use. Could you show example of using saved Access and Session Token, please?

**Comment by Crunchyman-ralph** [comment]
Having the same issue, works on index, but as soon as I want to navigate anywhere else, I get the error: 
```
InternalServerError: Cannot complete OAuth process. Could not find an OAuth cookie for shop url: XXX.myshopify.com
┃       at Object.throw (C:\xxx\xxx\Documents\GitHub\xxx\node_modules\koa\lib\context.js:97:11)
┃       at C:\xxx\xxx\Documents\GitHub\xxx\node_modules\@shopify\koa-shopify-auth\dist\src\auth\index.js:100:42
┃       at step (C:\xxx\xxx\Documents\GitHub\xxx\node_modules\tslib\tslib.js:141:27)
┃       at Object.throw (C:\xxx\xxx\Documents\GitHub\xxx\node_modules\tslib\tslib.js:122:57)
┃       at rejected (C:\xxx\xxx\Documents\GitHub\xxx\node_modules\tslib\tslib.js:113:69)
┃       at runMicrotasks (<anonymous>)
┃       at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Would love to get an insight as to what might be going on.

**Comment by hbittelbrunn** [comment]
I was having the same issue, in my case, it was related to Navigation config in the App Extention in the Partner Portal. 
I was pointing to the "/index" and the app was actually routing to "index/index.js", making the Nav get stuck. Refreshing the page was breaking the OAuth process returning the Internal Server Error (OAuth) described above.  Removing the "/index" from the Nav config in the Partner portal fixed my issue. 
Not sure if your issue is the same, just sharing my case.

**Comment by valorloff** [comment]
Yes, this solved! 
I also leaning towards this conclusion before your post

**Comment by akhilmhdh** [comment]
Hi @valorloff  Did u fixed this issue.

 Suddenly my app in development is also firing this error saying
```
  InternalServerError: Cannot complete OAuth process. Could not find an OAuth cookie for shop url: 
```

Can someone address why this error happens. I am following the latest node + react demo using memory session and online token.

**Comment by valorloff** [comment]
Hi @akhilmhdh! the problem lies somewhere inside `@shopify/koa-shopify-auth`, it takes a lot of time to resume work, you need full page reload, over and over again

**Comment by akhilmhdh** [comment]
I actually really dont know. Shopify just keeps on redirecting me to this section, and then fails as the domain is invalid.

**Comment by tmstn** [comment]
@akhilmhdh I was having the same issue as you but I solved it by making my app use https on localhost with a self signed certificate. You may find that you will encounter #564 after solving this though.

**Comment by palashkulsh** [comment]
for anyone facing the error that shopify is redirecting you to localhost:8081 even when HOST variable is set correctly in .env file **and you are nginx to proxy requests** then I solved the issue by passing host header from nginx proxypass

`    server {
        listen 443 ssl default;
        listen [::]:443 ssl;
        include snippets/self-signed.conf;
        include snippets/ssl-params.conf;

        server_name example.com www.example.com ;
        proxy_set_header Host "$http_host";
        location / {
                proxy_pass http://localhost:8081;
        }
` 

This was happening because apparently shopify creates a html script tag response using location header.

**Comment by nandumoura** [comment]
> I was having the same issue, in my case, it was related to Navigation config in the App Extention in the Partner Portal. I was pointing to the "/index" and the app was actually routing to "index/index.js", making the Nav get stuck. Refreshing the page was breaking the OAuth process returning the Internal Server Error (OAuth) described above. Removing the "/index" from the Nav config in the Partner portal fixed my issue. Not sure if your issue is the same, just sharing my case.

Thanks this solve for me
