### ISSUE TITLE
ECMAScript Module syntax

### ISSUE THREAD

**Issue by rheemy** [Shopify/shopify-app-node#688]
# Issue summary

After following the Shopify 'create an app' steps and using the CLI to clone the shopify node app, I have been unable to run the `shopify app serve` command without exceptioning with ECMAScript module syntax errors. 

- Node version: 17.3.0
- NPM version: 8.3.0
- Windows 10

## Expected behavior

A user should be able to clone/fork the code, and use the shopify CLI to serve the application locally without code changes.

## Actual behavior
`npm run dev` throws the following error (idk why code blocks are borked here so prepare yourself)
<details>
 ``` > shopify-app-node@1.0.0 dev

> cross-env NODE_ENV=development nodemon ./server/index.js --watch ./server/index.js

[nodemon] 2.0.15
[nodemon] to restart at any time, enter \`rs\`
[nodemon] watching path(s): server\index.js
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./server/index.js`
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
node:internal/modules/cjs/loader:488
      throw e;
      ^

Error: Package subpath './lib/parser' is not defined by "exports" in C:\PATH\TO\CODE\node_modules\next\node_modules\postcss\package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.552 (C:\PATH\TO\CODE\node_modules\next\dist\compiled\postcss-scss\scss-syntax.js:1:11590)
    at __webpack_require__ (C:\PATH\TO\CODE\node_modules\next\dist\compiled\postcss-scss\scss-syntax.js:1:11735)
    at Object.560 (C:\PATH\TO\CODE\node_modules\next\dist\compiled\postcss-scss\scss-syntax.js:1:400)
    at __webpack_require__ (C:\PATH\TO\CODE\node_modules\next\dist\compiled\postcss-scss\scss-syntax.js:1:11735)
    at Object.290 (C:\PATH\TO\CODE\node_modules\next\dist\compiled\postcss-scss\scss-syntax.js:1:260)
    at __webpack_require__ (C:\PATH\TO\CODE\node_modules\next\dist\compiled\postcss-scss\scss-syntax.js:1:11735)
    at Object.632 (C:\PATH\TO\CODE\node_modules\next\dist\compiled\postcss-scss\scss-syntax.js:1:3733) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
Node.js v17.3.0
[nodemon] app crashed - waiting for file changes before starting... ```
</details>

It's highly likely that this is related to the installed node version being sad about syntax changes. If that is the case, there should probably be a 'recommended' node version in the readme for users, as at the moment 17.3.0 is the recommended downloaded straight from nodejs.org. I updated from v8 after realising how blindingly old & incompatible my version was before immediately running into this.

**Comment by Michael-Gibbons** [comment]
@rheemy I believe you're absolutely correct. Using node v17 does cause errors while v16 does not. In general it is better to use the LTS node recommendation, currently `16.14.0`, rather than the newest version unless you're getting the newest version specifically to use the new features. 

NextJS in particular requires a node version of v12 or later. So anything between v12 and v16 inclusive should work. I just tested it on v10 and it also worked. So within reason its really only v17 which isn't supported yet. Node themselves confirmed that v17 has major breaking changes [here](https://medium.com/the-node-js-collection/node-js-17-is-here-8dba1e14e382). So its just going to take a while for packages to catch up.

But I agree with you that adding a recommended node version in the readme is probably the right thing to do.

**Comment by rheemy** [comment]
Apologies Michael, I did land on swapping back to the recommended version of Node which absolutely fixed the issue. I cleverly forgot to come back here with an update and mark the issue as resolved. 
Thanks for updating the Readme :)
